---
AWSTemplateFormatVersion: '2010-09-09'
Description: Provision accounts using Control Tower account factory

Parameters:
  SSOUserFirstName:
    Description:  "SSO user first name."
    Type: String
    AllowedPattern : ".+"
  SSOUserLastName:
    Description:  "SSO user last name."
    Type: String
    AllowedPattern : ".+"
  SSOUserEmail:
    Description: "SSO user email. A new SSO user will be created for this email if it does not exist. This SSO user will be associated with new accounts."
    Type: String
    AllowedPattern : "[^\\s@]+@[^\\s@]+\\.[^\\s@]+"
  SharedOrganizationalUnit:
    Description: "Managed organizational unit. The accounts will be placed under this Organizational Unit."
    Type: String
  WorkloadsOrganizationalUnit:
    Description: "Managed organizational unit. The accounts will be placed under this Organizational Unit."
    Type: String
  ProvisioningArtifactId:
    Description: ID the the product artifact/version
    Type: String
    AllowedPattern : ".+"
  ProvisioningProductId:
    Description: ID the the product
    Type: String
    AllowedPattern : ".+"

Resources:
  OperationsAccount:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      ProductId: !Ref ProvisioningProductId
      ProvisionedProductName: Operations
      ProvisioningArtifactId: !Ref ProvisioningArtifactId
      ProvisioningParameters:
      - Key: AccountName
        Value: Operations
      - Key: AccountEmail
        Value: "__ACCOUNT_EMAIL_PREFIX__operations__ACCOUNT_EMAIL_SUFFIX__"
      - Key: SSOUserFirstName
        Value: !Ref SSOUserFirstName
      - Key: SSOUserLastName
        Value: !Ref SSOUserLastName
      - Key: SSOUserEmail
        Value: !Ref SSOUserEmail
      - Key: ManagedOrganizationalUnit
        Value: !Ref SharedOrganizationalUnit
  SandboxAccount:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      ProductId: !Ref ProvisioningProductId
      ProvisionedProductName: Sandbox
      ProvisioningArtifactId: !Ref ProvisioningArtifactId
      ProvisioningParameters:
      - Key: AccountName
        Value: Sandbox
      - Key: AccountEmail
        Value: "__ACCOUNT_EMAIL_PREFIX__sandbox__ACCOUNT_EMAIL_SUFFIX__"
      - Key: SSOUserFirstName
        Value: !Ref SSOUserFirstName
      - Key: SSOUserLastName
        Value: !Ref SSOUserLastName
      - Key: SSOUserEmail
        Value: !Ref SSOUserEmail
      - Key: ManagedOrganizationalUnit
        Value: !Ref WorkloadsOrganizationalUnit
    DependsOn: OperationsAccount
  ProductionAccount:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      ProductId: !Ref ProvisioningProductId
      ProvisionedProductName: Production
      ProvisioningArtifactId: !Ref ProvisioningArtifactId
      ProvisioningParameters:
      - Key: AccountName
        Value: Production
      - Key: AccountEmail
        Value: "__ACCOUNT_EMAIL_PREFIX__production__ACCOUNT_EMAIL_SUFFIX__"
      - Key: SSOUserFirstName
        Value: !Ref SSOUserFirstName
      - Key: SSOUserLastName
        Value: !Ref SSOUserLastName
      - Key: SSOUserEmail
        Value: !Ref SSOUserEmail
      - Key: ManagedOrganizationalUnit
        Value: !Ref WorkloadsOrganizationalUnit
    DependsOn: SandboxAccount
  NetworkAccount:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      ProductId: !Ref ProvisioningProductId
      ProvisionedProductName: Network
      ProvisioningArtifactId: !Ref ProvisioningArtifactId
      ProvisioningParameters:
      - Key: AccountName
        Value: Network
      - Key: AccountEmail
        Value: "__ACCOUNT_EMAIL_PREFIX__network__ACCOUNT_EMAIL_SUFFIX__"
      - Key: SSOUserFirstName
        Value: !Ref SSOUserFirstName
      - Key: SSOUserLastName
        Value: !Ref SSOUserLastName
      - Key: SSOUserEmail
        Value: !Ref SSOUserEmail
      - Key: ManagedOrganizationalUnit
        Value: !Ref SharedOrganizationalUnit
    DependsOn: ProductionAccount
  BackupAccount:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      ProductId: !Ref ProvisioningProductId
      ProvisionedProductName: Backup
      ProvisioningArtifactId: !Ref ProvisioningArtifactId
      ProvisioningParameters:
      - Key: AccountName
        Value: Backup
      - Key: AccountEmail
        Value: "__ACCOUNT_EMAIL_PREFIX__backup__ACCOUNT_EMAIL_SUFFIX__"
      - Key: SSOUserFirstName
        Value: !Ref SSOUserFirstName
      - Key: SSOUserLastName
        Value: !Ref SSOUserLastName
      - Key: SSOUserEmail
        Value: !Ref SSOUserEmail
      - Key: ManagedOrganizationalUnit
        Value: !Ref SharedOrganizationalUnit
    DependsOn: NetworkAccount
  IdentityAccount:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      ProductId: !Ref ProvisioningProductId
      ProvisionedProductName: Identity
      ProvisioningArtifactId: !Ref ProvisioningArtifactId
      ProvisioningParameters:
      - Key: AccountName
        Value: Identity
      - Key: AccountEmail
        Value: "__ACCOUNT_EMAIL_PREFIX__identity__ACCOUNT_EMAIL_SUFFIX__"
      - Key: SSOUserFirstName
        Value: !Ref SSOUserFirstName
      - Key: SSOUserLastName
        Value: !Ref SSOUserLastName
      - Key: SSOUserEmail
        Value: !Ref SSOUserEmail
      - Key: ManagedOrganizationalUnit
        Value: !Ref SharedOrganizationalUnit
    DependsOn: BackupAccount
